FROM golang:1.23-alpine as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o lighthouse ./cmd/lighthouse.go

FROM alpine:3.20.3
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/lighthouse .
RUN chmod +x /app/lighthouse

CMD ["/app/lighthouse"]
